#ifndef L_SUPPORT_DOCUMENT

#define L_SUPPORT_DOCUMENT 0
#define L_SUPPORT_GIFLZW 1
#define L_SUPPORT_TIFLZW 2
#define L_SUPPORT_FPXEXTENSIONS 3
#define L_SUPPORT_OCR 4
#define L_SUPPORT_MULTIMEDIA 5
#define L_SUPPORT_MEDICAL 6
#define L_SUPPORT_JBIG 7
#define L_SUPPORT_VECTOR 8
#define L_SUPPORT_MEDICAL_NET 9
#define L_SUPPORT_BARCODES_1D 10
#define L_SUPPORT_BARCODES_2D_READ 11
#define L_SUPPORT_BARCODES_2D_WRITE 12
#define L_SUPPORT_BARCODES_PDF_READ 13
#define L_SUPPORT_BARCODES_PDF_WRITE 14
#define L_SUPPORT_INTERNET 15
#define L_SUPPORT_VECTOR_DWG 16
#define L_SUPPORT_VECTOR_DXF 17
#define L_SUPPORT_VECTOR_MISC 18
#define L_SUPPORT_VECTOR_ALL 19
#define L_SUPPORT_VECTOR_DWF 20
#define L_SUPPORT_RESERVED1 21
#define L_SUPPORT_PDF 22
#define L_SUPPORT_VECTOR_VIEW 23
#define L_SUPPORT_DIGITALPAINT 24
#define L_SUPPORT_J2K 25
#define L_SUPPORT_CMW 26
#define L_SUPPORT_MAX 26

#endif
